server:
  port: 9010 #配置端口
  session-timeout: 30
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

